import sqlite3
DB_NAME="arcade.db"
connection=sqlite3.connect(DB_NAME)
cursor=connection.cursor()
cursor.execute("INSERT INTO arcade (name,coin_cost) VALUES (?,?)",("Fast Reaction",2))
cursor.execute("INSERT INTO arcade(name,coin_cost) VALUES(?,?)",("Air Hockey",3))
cursor.execute("INSERT INTO arcade(name,coin_cost) VALUES(?,?)",("Basketball",3))
cursor.execute("INSERT INTO arcade(name,coin_cost) VALUES(?,?)",("Alien Extermination",3))
cursor.execute("INSERT INTO arcade(name,coin_cost) VALUES(?,?)",("Boxing",2))
cursor.execute("INSERT INTO snacks(name,price) VALUES(?,?)",("Monster",260))
cursor.execute("INSERT INTO snacks(name,price) VALUES(?,?)",("Fanta",100))
cursor.execute("INSERT INTO snacks(name,price) VALUES(?,?)",("Predator",100))
cursor.execute("INSERT INTO snacks(name,price) VALUES(?,?)",("Coke",100))
cursor.execute("INSERT INTO snacks(name,price) VALUES(?,?)",("Sprite",100))
cursor.execute("INSERT INTO snacks(name,price) VALUES(?,?)",("Water",80))
cursor.execute("INSERT INTO stations(name,type,hourly_rate,ip_address) VALUES(?,?,?,?)",("Console 1","console",1000,"192.168.1.101"))
cursor.execute("INSERT INTO stations(name,type,hourly_rate,ip_address) VALUES(?,?,?,?)",("Console 2","console",1000,"192.168.1.102"))
cursor.execute("INSERT INTO stations(name,type,hourly_rate,ip_address) VALUES(?,?,?,?)",("Console 3","console",1000,"192.168.1.103"))
cursor.execute("INSERT INTO stations(name,type,hourly_rate,ip_address) VALUES(?,?,?,?)",("Racing 1","racing",1300,"192.168.1.104"))
cursor.execute("INSERT INTO stations(name,type,hourly_rate,ip_address) VALUES(?,?,?,?)",("Racing 2","racing",1300,"192.168.1.105"))
cursor.execute("INSERT INTO stations(name,type,hourly_rate,ip_address) VALUES(?,?,?,?)",("Racing 3","racing",1300,"192.168.1.106"))
connection.commit()
connection.close()
print("Sample data inserted successfully!")